application: i-littlecircle
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: ../public/js
- url: /.*
  script: littlecircle.app

libraries:
# https://developers.google.com/appengine/docs/python/tools/libraries27
- name: webapp2
  version: 2.5.2
- name: PIL
  version: latest
- name: webob
  version: latest